---
- hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Contoh Menambahkan Bridge Interface
    routeros_command:
      commands: interface bridge add name=demo_bridge
